import type {
  StrategyFixtureCatalog,
  StrategyLabDetail,
  StrategyLabViewModel,
  StrategyStatus,
} from "../../domain/strategy";
import { toStrategyLabViewModel } from "../../domain/strategy";

function detail(
  input: Omit<StrategyLabDetail, "paperBets"> & { paperBets?: StrategyLabDetail["paperBets"] },
): StrategyLabDetail {
  return {
    ...input,
    paperBets: input.paperBets ?? [],
  };
}

export const strategyLabFixtures: StrategyFixtureCatalog = {
  spread_edge_v1: {
    strategyId: "spread_edge_v1",
    displayName: "Spread Edge",
    weight: 0.32,
    netGp30d: 64200,
    accuracy30d: 0.66,
    currentConfidence: 0.71,
    status: "active",
    bestRegime: "Steady demand",
    worstRegime: "Thin overnight liquidity",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: true,
    disabledReason: null,
    detail: detail({
      strategyId: "spread_edge_v1",
      displayName: "Spread Edge",
      summary: "Best when after-tax upside is still practical to trade.",
      whatItLooksFor: "Spread edge, realistic fills, and recent accuracy that still holds up.",
      currentWeightLabel: "32% of current blended votes",
      recentPerformanceLabel: "Net +64,200 gp over the last 30 days",
      bestRegime: "Steady demand",
      worstRegime: "Thin overnight liquidity",
      currentConfidenceLabel: "71%",
      configSummary: [
        "Requires positive after-tax edge.",
        "Downweights weak fill confidence.",
        "Prefers recent evidence over stale momentum.",
      ],
      advanced: {
        strategyId: "spread_edge_v1",
        modelVersion: "v1",
        configJson: JSON.stringify({ minEdgeBps: 85, minFillProbability: 0.48, horizonSecs: 7200 }, null, 2),
        statusNote: null,
      },
      paperBets: [
        { itemName: "Abyssal whip", actionLabel: "BUY", outcomeLabel: "Exited in profit", netGp: 3200, confidence: 0.74 },
        { itemName: "Dragon boots", actionLabel: "BUY", outcomeLabel: "Stopped out", netGp: -900, confidence: 0.62 },
        { itemName: "Saradomin brew(4)", actionLabel: "SELL", outcomeLabel: "Protected profit", netGp: 2100, confidence: 0.69 },
        { itemName: "Zulrah's scales", actionLabel: "WAIT", outcomeLabel: "Skipped due to weak fills", netGp: null, confidence: 0.48 },
        { itemName: "Rune dart tips", actionLabel: "BUY", outcomeLabel: "Small gain", netGp: 650, confidence: 0.58 },
        { itemName: "Mahogany plank", actionLabel: "BUY", outcomeLabel: "Held too long", netGp: -440, confidence: 0.52 },
        { itemName: "Prayer potion(4)", actionLabel: "SELL", outcomeLabel: "Strong cashout", netGp: 1840, confidence: 0.77 },
        { itemName: "Cannonball", actionLabel: "BUY", outcomeLabel: "Flat exit", netGp: 120, confidence: 0.55 },
        { itemName: "Shark", actionLabel: "SELL", outcomeLabel: "Protected profit", netGp: 980, confidence: 0.68 },
        { itemName: "Amylase crystal", actionLabel: "BUY", outcomeLabel: "Met target", netGp: 1460, confidence: 0.73 },
      ],
    }),
  },
  momentum_v1: {
    strategyId: "momentum_v1",
    displayName: "Momentum",
    weight: 0.19,
    netGp30d: 14800,
    accuracy30d: 0.54,
    currentConfidence: 0.63,
    status: "degraded",
    bestRegime: "Fast trend continuation",
    worstRegime: "Violent reversals",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: true,
    disabledReason: "Recent confidence has outrun realized outcomes.",
    detail: detail({
      strategyId: "momentum_v1",
      displayName: "Momentum",
      summary: "Useful when a move keeps carrying, but currently under review.",
      whatItLooksFor: "Continuation after strong direction with enough trade capacity left.",
      currentWeightLabel: "19% of current blended votes",
      recentPerformanceLabel: "Net +14,800 gp over the last 30 days",
      bestRegime: "Fast trend continuation",
      worstRegime: "Violent reversals",
      currentConfidenceLabel: "63%",
      configSummary: [
        "Requires repeated upward or downward follow-through.",
        "Cuts weight when reversals increase.",
      ],
      advanced: {
        strategyId: "momentum_v1",
        modelVersion: "v2",
        configJson: JSON.stringify({ minTrendScore: 0.62, cooldownBuckets: 2 }, null, 2),
        statusNote: "Flagged degraded because recent confidence has outrun realized outcomes.",
      },
    }),
  },
  mean_reversion_v1: {
    strategyId: "mean_reversion_v1",
    displayName: "Mean Reversion",
    weight: null,
    netGp30d: null,
    accuracy30d: null,
    currentConfidence: 0.41,
    status: "insufficient_data",
    bestRegime: "Short panic snaps back",
    worstRegime: "Strong one-way trend",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: true,
    disabledReason: "Not enough recent examples yet.",
    detail: detail({
      strategyId: "mean_reversion_v1",
      displayName: "Mean Reversion",
      summary: "Looks for stretched moves that may snap back, but sample size is still thin.",
      whatItLooksFor: "Temporary overshoots that unwind before the broader market re-prices.",
      currentWeightLabel: null,
      recentPerformanceLabel: null,
      bestRegime: "Short panic snaps back",
      worstRegime: "Strong one-way trend",
      currentConfidenceLabel: "41%",
      configSummary: [
        "Needs more recent trades before accuracy becomes meaningful.",
        "Suppresses itself when trend pressure stays one-sided.",
      ],
      advanced: {
        strategyId: "mean_reversion_v1",
        modelVersion: "v1",
        configJson: JSON.stringify({ maxTrendPressure: 0.45, minOvershootZ: 1.35 }, null, 2),
        statusNote: "Recent sample size is too small to treat its metrics as stable.",
      },
    }),
  },
  kalman_fair_value_v1: {
    strategyId: "kalman_fair_value_v1",
    displayName: "Kalman Fair Value",
    weight: 0.11,
    netGp30d: 9100,
    accuracy30d: 0.6,
    currentConfidence: 0.58,
    status: "active",
    bestRegime: "Slow drift back to fair value",
    worstRegime: "Shock repricing",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: true,
    disabledReason: null,
    detail: detail({
      strategyId: "kalman_fair_value_v1",
      displayName: "Kalman Fair Value",
      summary: "Tracks a fair-value estimate and waits for price to rejoin it.",
      whatItLooksFor: "Price drifting away from estimated fair value without a fresh structural reason.",
      currentWeightLabel: "11% of current blended votes",
      recentPerformanceLabel: "Net +9,100 gp over the last 30 days",
      bestRegime: "Slow drift back to fair value",
      worstRegime: "Shock repricing",
      currentConfidenceLabel: "58%",
      configSummary: ["Relies on smoother fair-value tracking.", "Downweights abrupt structural shifts."],
      advanced: {
        strategyId: "kalman_fair_value_v1",
        modelVersion: "v1",
        configJson: JSON.stringify({ processNoise: 0.06, measurementNoise: 0.14 }, null, 2),
        statusNote: null,
      },
    }),
  },
  regime_detector_v1: {
    strategyId: "regime_detector_v1",
    displayName: "Regime Detector",
    weight: 0.08,
    netGp30d: 4800,
    accuracy30d: 0.57,
    currentConfidence: 0.53,
    status: "active",
    bestRegime: "Range-bound calm",
    worstRegime: "Sudden event shock",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: true,
    disabledReason: null,
    detail: detail({
      strategyId: "regime_detector_v1",
      displayName: "Regime Detector",
      summary: "Classifies the current market mood so other methods can scale sensibly.",
      whatItLooksFor: "Whether current conditions are calm, trending, stressed, or unstable.",
      currentWeightLabel: "8% of current blended votes",
      recentPerformanceLabel: "Net +4,800 gp over the last 30 days",
      bestRegime: "Range-bound calm",
      worstRegime: "Sudden event shock",
      currentConfidenceLabel: "53%",
      configSummary: ["Acts as an overlay rather than a primary trade engine."],
      advanced: {
        strategyId: "regime_detector_v1",
        modelVersion: "v1",
        configJson: JSON.stringify({ stressThreshold: 0.72, calmThreshold: 0.38 }, null, 2),
        statusNote: null,
      },
    }),
  },
  gbm_ranker_v1: {
    strategyId: "gbm_ranker_v1",
    displayName: "Gradient Ranker",
    weight: 0.09,
    netGp30d: 20600,
    accuracy30d: 0.64,
    currentConfidence: 0.67,
    status: "active",
    bestRegime: "Broad cross-item agreement",
    worstRegime: "Schema drift",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: false,
    disabledReason: "Artifact-backed methods remain locked until validated exports are present.",
    detail: detail({
      strategyId: "gbm_ranker_v1",
      displayName: "Gradient Ranker",
      summary: "Ranks opportunities across items when artifact-backed features stay aligned.",
      whatItLooksFor: "Cross-item patterns that a learned ranker still recognizes cleanly.",
      currentWeightLabel: "9% of current blended votes",
      recentPerformanceLabel: "Net +20,600 gp over the last 30 days",
      bestRegime: "Broad cross-item agreement",
      worstRegime: "Schema drift",
      currentConfidenceLabel: "67%",
      configSummary: ["Locked until the exported artifact contract validates."],
      advanced: {
        strategyId: "gbm_ranker_v1",
        modelVersion: "artifact/v1",
        configJson: JSON.stringify({ artifact: "gbm_ranker_v1", schemaHash: "fixture-hash" }, null, 2),
        statusNote: "Toggle is disabled because artifact-backed methods remain locked by runtime policy.",
      },
    }),
  },
  contextual_bandit_v1: {
    strategyId: "contextual_bandit_v1",
    displayName: "Contextual Bandit",
    weight: 0.05,
    netGp30d: 11600,
    accuracy30d: 0.59,
    currentConfidence: 0.56,
    status: "active",
    bestRegime: "Fast feedback",
    worstRegime: "Sparse outcomes",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: false,
    disabledReason: "Artifact-backed methods remain locked until validated exports are present.",
    detail: detail({
      strategyId: "contextual_bandit_v1",
      displayName: "Contextual Bandit",
      summary: "Shifts weight between choices when outcome feedback arrives quickly enough.",
      whatItLooksFor: "Action choices that improve with short-loop outcome feedback.",
      currentWeightLabel: "5% of current blended votes",
      recentPerformanceLabel: "Net +11,600 gp over the last 30 days",
      bestRegime: "Fast feedback",
      worstRegime: "Sparse outcomes",
      currentConfidenceLabel: "56%",
      configSummary: ["Locked until the exported artifact contract validates."],
      advanced: {
        strategyId: "contextual_bandit_v1",
        modelVersion: "artifact/v1",
        configJson: JSON.stringify({ artifact: "contextual_bandit_v1", exploration: 0.1 }, null, 2),
        statusNote: "Toggle is disabled because artifact-backed methods remain locked by runtime policy.",
      },
    }),
  },
  meta_label_v1: {
    strategyId: "meta_label_v1",
    displayName: "Meta Label Filter",
    weight: 0.04,
    netGp30d: 7200,
    accuracy30d: 0.55,
    currentConfidence: 0.51,
    status: "active",
    bestRegime: "Good base-signal agreement",
    worstRegime: "Contradictory evidence",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: false,
    disabledReason: "Artifact-backed methods remain locked until validated exports are present.",
    detail: detail({
      strategyId: "meta_label_v1",
      displayName: "Meta Label Filter",
      summary: "Acts as a last filter on whether another method should really take the trade.",
      whatItLooksFor: "Signals that should be filtered out despite looking attractive on the surface.",
      currentWeightLabel: "4% of current blended votes",
      recentPerformanceLabel: "Net +7,200 gp over the last 30 days",
      bestRegime: "Good base-signal agreement",
      worstRegime: "Contradictory evidence",
      currentConfidenceLabel: "51%",
      configSummary: ["Locked until the exported artifact contract validates."],
      advanced: {
        strategyId: "meta_label_v1",
        modelVersion: "artifact/v1",
        configJson: JSON.stringify({ artifact: "meta_label_v1", threshold: 0.58 }, null, 2),
        statusNote: "Toggle is disabled because artifact-backed methods remain locked by runtime policy.",
      },
    }),
  },
  conformal_uncertainty_v1: {
    strategyId: "conformal_uncertainty_v1",
    displayName: "Conformal Uncertainty",
    weight: 0.06,
    netGp30d: 5300,
    accuracy30d: 0.58,
    currentConfidence: 0.49,
    status: "active",
    bestRegime: "Stable error bands",
    worstRegime: "Sudden volatility spike",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: true,
    disabledReason: null,
    detail: detail({
      strategyId: "conformal_uncertainty_v1",
      displayName: "Conformal Uncertainty",
      summary: "Widens or tightens trust based on how honest recent error bands have been.",
      whatItLooksFor: "Whether likely-range estimates have stayed honest enough to trust.",
      currentWeightLabel: "6% of current blended votes",
      recentPerformanceLabel: "Net +5,300 gp over the last 30 days",
      bestRegime: "Stable error bands",
      worstRegime: "Sudden volatility spike",
      currentConfidenceLabel: "49%",
      configSummary: ["Used as an uncertainty overlay more than a direct signal."],
      advanced: {
        strategyId: "conformal_uncertainty_v1",
        modelVersion: "v1",
        configJson: JSON.stringify({ miscoverageTarget: 0.12, trailingWindow: 120 }, null, 2),
        statusNote: null,
      },
    }),
  },
  portfolio_optimizer_v1: {
    strategyId: "portfolio_optimizer_v1",
    displayName: "Portfolio Optimizer",
    weight: 0.06,
    netGp30d: 13800,
    accuracy30d: 0.61,
    currentConfidence: 0.6,
    status: "active",
    bestRegime: "Many decent choices",
    worstRegime: "Single concentrated market theme",
    lastUpdatedAt: "2026-06-17T08:00:00Z",
    canToggle: true,
    disabledReason: null,
    detail: detail({
      strategyId: "portfolio_optimizer_v1",
      displayName: "Portfolio Optimizer",
      summary: "Sizes opportunities so the overall basket stays more balanced.",
      whatItLooksFor: "How to spread capital across attractive items without overconcentrating risk.",
      currentWeightLabel: "6% of current blended votes",
      recentPerformanceLabel: "Net +13,800 gp over the last 30 days",
      bestRegime: "Many decent choices",
      worstRegime: "Single concentrated market theme",
      currentConfidenceLabel: "60%",
      configSummary: ["Acts on top of the live recommendation mix rather than replacing it."],
      advanced: {
        strategyId: "portfolio_optimizer_v1",
        modelVersion: "v1",
        configJson: JSON.stringify({ maxItemWeight: 0.28, turnoverPenalty: 0.12 }, null, 2),
        statusNote: null,
      },
    }),
  },
};

export const strategyLabFixtureStatuses: StrategyStatus[] = [
  { strategyId: "spread_edge_v1", enabled: true },
  { strategyId: "momentum_v1", enabled: true },
  { strategyId: "mean_reversion_v1", enabled: true },
  { strategyId: "kalman_fair_value_v1", enabled: true },
  { strategyId: "regime_detector_v1", enabled: true },
  { strategyId: "gbm_ranker_v1", enabled: false },
  { strategyId: "contextual_bandit_v1", enabled: false },
  { strategyId: "meta_label_v1", enabled: false },
  { strategyId: "conformal_uncertainty_v1", enabled: true },
  { strategyId: "portfolio_optimizer_v1", enabled: true },
];

export const strategyLabViewFixture: StrategyLabViewModel = toStrategyLabViewModel(
  strategyLabFixtureStatuses,
  strategyLabFixtures,
);
