import type { ModelAccuracyViewModel, TrustSummaryViewModel } from "../../domain/modelAccuracy";

const spreadEdgeWeek: ModelAccuracyViewModel = {
  strategyId: "spread_edge_v1",
  modelVersion: "v1",
  windowLabel: "7d",
  sampleSize: 24,
  directionalAccuracy: 0.66,
  brierScore: 0.18,
  netSimulatedGp: 18200,
  winRate: 0.61,
  profitFactor: 1.42,
  maxDrawdown: 0.11,
  avgTimeInTrade: "2h 20m",
  capitalEfficiency: 0.58,
  calibrationBuckets: [
    { label: "40-50%", predicted: 0.45, actual: 0.43, sampleSize: 8 },
    { label: "50-60%", predicted: 0.55, actual: 0.56, sampleSize: 9 },
    { label: "60-70%", predicted: 0.65, actual: 0.63, sampleSize: 7 },
  ],
  whatItDoes: "Looks for after-tax edge that still seems practical to trade.",
  worksBestWhen: "Prices are fresh, spread is usable, and similar recent calls have behaved consistently.",
  weakness: "It weakens quickly when fills look uncertain or the sample size is thin.",
};

export const modelAccuracyFixtures: ModelAccuracyViewModel[] = [
  spreadEdgeWeek,
  {
    ...spreadEdgeWeek,
    windowLabel: "30d",
    sampleSize: 81,
    directionalAccuracy: 0.64,
    brierScore: 0.2,
    netSimulatedGp: 52200,
    winRate: 0.59,
    profitFactor: 1.34,
    maxDrawdown: 0.15,
    avgTimeInTrade: "2h 50m",
    capitalEfficiency: 0.55,
  },
  {
    ...spreadEdgeWeek,
    windowLabel: "all",
    sampleSize: 164,
    directionalAccuracy: 0.62,
    brierScore: 0.22,
    netSimulatedGp: 101400,
    winRate: 0.57,
    profitFactor: 1.28,
    maxDrawdown: 0.19,
    avgTimeInTrade: "3h 05m",
    capitalEfficiency: 0.51,
  },
  {
    ...spreadEdgeWeek,
    strategyId: "momentum_v1",
    modelVersion: "v2",
    windowLabel: "7d",
    directionalAccuracy: 0.57,
    winRate: 0.54,
    profitFactor: 1.08,
    calibrationBuckets: [
      { label: "60-70%", predicted: 0.65, actual: 0.42, sampleSize: 8 },
      { label: "70-80%", predicted: 0.75, actual: 0.49, sampleSize: 8 },
      { label: "80-90%", predicted: 0.85, actual: 0.52, sampleSize: 8 },
    ],
    whatItDoes: "Follows recent direction when the move still looks tradable after fees.",
    worksBestWhen: "A strong move keeps carrying without collapsing on the next snapshot.",
    weakness: "It can sound too certain when the move cools off quickly.",
  },
  {
    ...spreadEdgeWeek,
    strategyId: "mean_reversion_v1",
    windowLabel: "7d",
    sampleSize: 6,
    directionalAccuracy: 0.5,
    calibrationBuckets: [
      { label: "50-60%", predicted: 0.55, actual: 0.5, sampleSize: 3 },
      { label: "60-70%", predicted: 0.65, actual: null, sampleSize: 3 },
    ],
    whatItDoes: "Looks for short-term snapback after a stretched move.",
    worksBestWhen: "Spikes fade quickly and spreads stay modest.",
    weakness: "It needs more fresh examples before we should trust it.",
  },
  {
    ...spreadEdgeWeek,
    strategyId: "volatility_filter_v1",
    windowLabel: "7d",
    directionalAccuracy: null,
    brierScore: null,
    netSimulatedGp: null,
    winRate: null,
    profitFactor: null,
    maxDrawdown: null,
    avgTimeInTrade: null,
    capitalEfficiency: null,
    calibrationBuckets: [{ label: "60-70%", predicted: 0.65, actual: null, sampleSize: 0 }],
    whatItDoes: "Keeps high-noise conditions from becoming overconfident trades.",
    worksBestWhen: "It supports other methods during unstable periods.",
    weakness: "By itself it does not provide enough outcome history yet.",
  },
];

export const trustSummaryFixture: TrustSummaryViewModel = {
  buyCallsProfitable: 61,
  sellCallsProtectedProfit: 58,
  averageProfitPerSuccessfulCall: 1520,
  bestMethodThisWeek: "spread_edge_v1",
  weakestMethodThisWeek: "volatility_filter_v1",
  confidenceHonestySentence: "When GrandEdge said 60-70% confident, it was right about 63% of the time.",
};
